#!/bin/bash

main() {
    local -a crabs=($(grep ',' input | tr ',' '\n'))
    local -i min=9999999
    local -i max=0

    for crab in ${crabs[@]}; do
        if test $crab -gt $max; then
            max=$crab
        fi

        if test $crab -lt $min; then
            min=$crab
        fi
    done

    echo "Min is $min, max=$max"

    minFuel=9999999
    for ((index=min; index <= max; ++index)); do
        fuel=0

        for crab in ${crabs[@]}; do
            thisFuel=$((crab - index))

            # Get abs of minFuel and add to fuel
            ((fuel += ${thisFuel#-}))
        done

        echo "Fuel at index $index is $fuel"
        if test $fuel -lt $minFuel; then
            minFuel=$fuel
        fi
    done

    echo "Minimum fuel needed is $minFuel"
}

main "$@"
