#!/bin/bash

main() {
    local -i count=0

    while read line; do
        local -a signals=($(echo $line | cut -d'|' -f1))
        local -a outputs=($(echo $line | cut -d'|' -f2))

        for output in ${outputs[@]}; do
            if test ${#output} -eq 2 -o \
                    ${#output} -eq 3 -o \
                    ${#output} -eq 4 -o \
                    ${#output} -eq 7; then
                ((++count))
            fi
        done
    done < input

    echo "Number of 1, 4, 7 or 8s is $count"
}

main "$@"
