#!/bin/bash

forward=0
down=0

while read line; do
    direction="$(echo $line | cut -f1 -d" ")"
    magnitude="$(echo $line | cut -f2 -d" ")"

    if test "$direction" = "up"; then
        (( down -= magnitude ))
    elif test "$direction" = "down"; then
        (( down += magnitude ))
    else
        (( forward += magnitude ))
    fi
done < input

echo "result is $(( forward * down ))"